stages:
  - ci-image
  - wheels

variables:
  CURRENT_CI_IMAGE: 1
  SRC_PATH: /go/src/github.com/DataDog/integrations-core

before_script:
  - cd $SRC_PATH

ci-image:
  stage: ci-image
  when: manual
  except: [ tags, schedules ]
  tags: [ "runner:main", "size:large" ]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  services:
    - 486234852809.dkr.ecr.us-east-1.amazonaws.com/remote-docker:latest
  script:
    - docker build --tag 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/integrations-core:$CURRENT_CI_IMAGE .
    - docker push 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/integrations-core:$CURRENT_CI_IMAGE

wheels:
  stage: wheels
  only:
    - master
  tags: [ "runner:main", "size:large" ]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/integrations-core:$CURRENT_CI_IMAGE
  script:
    - CURRENT_REF=$(git rev-parse HEAD)
    - echo $CURRENT_REF
    - git pull origin master
    - git --no-pager log -n 12
    - git checkout $CURRENT_REF
    - git describe --abbrev=0 --tags
