parameters:
  test_run: ''
  check: ''
  test: false
  test_e2e: false
  benchmark: false

steps:

- ${{ if eq(parameters.test_e2e, 'true') }}:
  - script: ddev env test --base --new-env --junit ${{ parameters.check }} -a datadog/agent:6.16.1-rc.2
    displayName: 'Run E2E tests'
    env:
      DD_API_KEY: $(DD_API_KEY)
