parameters:
  test_run: ''
  check: ''
  test: false
  test_e2e: false
  benchmark: false

steps:

- ${{ if eq(parameters.test_e2e, 'true') }}:
  - script: "ddev env test --base --new-env --junit sqlserver:py37 --agent datadog/agent:7.16.1-rc.1"
    displayName: 'Run E2E tests Python 3'
    env:
      DD_API_KEY: $(DD_API_KEY)

- ${{ if eq(parameters.test_e2e, 'true') }}:
  - script: "ddev env test --base --new-env --junit sqlserver:py27 --agent datadog/agent:6.16.1-rc.1"
    displayName: 'Run E2E tests Python 2'
    env:
      DD_API_KEY: $(DD_API_KEY)
