parameters:
  job_name: ''
  check: ''
  display: ''
  test: true
  test_e2e: true
  benchmark: true
  validate: false
  repo: 'core'

jobs:
- job: '${{ coalesce(parameters.job_name, parameters.check) }}_Linux'
  displayName: '${{ parameters.display }}'

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - script: |
      echo '##vso[task.logissue type=warning]this is a warning'
      echo '##vso[task.logissue type=error]this is an error'
  - template: './checkout-code.yml'

  - template: './install-deps.yml'
    parameters:
      repo: ${{ parameters.repo }}

  - template: './set-up-integrations.yml'
    parameters:
      check: ${{ parameters.check }}

  - ${{ if eq(parameters.validate, 'true') }}:
    - template: './run-validations.yml'
      parameters:
        repo: ${{ parameters.repo }}

  - template: './run-tests.yml'
    parameters:
      test_run: '${{ coalesce(parameters.job_name, parameters.check) }}.linux'
      check: ${{ parameters.check }}
      test: ${{ parameters.test }}
      test_e2e: ${{ parameters.test_e2e }}
      benchmark: ${{ parameters.benchmark }}
      repo: ${{ parameters.repo }}
