pr:
  branches:
    include:
    - master
    - alex/before_import_issue
  paths:
    include:
    - datadog_checks_base/datadog_checks/*
    exclude:
    - datadog_checks_base/datadog_checks/base/data/agent_requirements.in

trigger: none

variables:
  DDEV_COLOR: 1

jobs:
- template: './templates/test-all-checks.yml'
