pr:
  branches:
    include:
    - master
  paths:
    include:
    - datadog_checks_base/datadog_checks/*
    exclude:
    - datadog_checks_base/datadog_checks/base/data/agent_requirements.in

trigger: none

variables:
  DDEV_COLOR: 1
  DDEV_E2E_AGENT: 7

jobs:
- template: './templates/test-all-checks.yml'
