trigger: none

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - datadog_checks_base/datadog_checks/*

variables:
  DDEV_COLOR: 1

jobs:
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Changed
    display: Linux
    validate: true

- template: './templates/test-single-windows.yml'
  parameters:
    job_name: Changed
    display: Windows
